// AUTO-GENERATED by scripts/gen-migrations.ts — do not edit.
// Regenerate via `bun run db:generate` (runs drizzle-kit generate + this script).
import type { MigrationMeta } from 'drizzle-orm/migrator';

export const MIGRATIONS: MigrationMeta[] = [
  {
    "sql": [
      "CREATE TABLE `pluts_accounts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`name` text NOT NULL,\n\t`type` text NOT NULL,\n\t`contra` integer DEFAULT false NOT NULL,\n\t`created_at` text NOT NULL,\n\tCONSTRAINT \"pluts_accounts_type_check\" CHECK(\"pluts_accounts\".\"type\" IN ('Asset','Liability','Equity','Revenue','Expense'))\n);\n",
      "\nCREATE UNIQUE INDEX `pluts_accounts_name_type_idx` ON `pluts_accounts` (`name`,`type`);",
      "\nCREATE INDEX `pluts_accounts_type_idx` ON `pluts_accounts` (`type`,`name`);",
      "\nCREATE TABLE `pluts_amounts` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`type` text NOT NULL,\n\t`account_id` text NOT NULL,\n\t`entry_id` text NOT NULL,\n\t`amount` integer NOT NULL,\n\tFOREIGN KEY (`account_id`) REFERENCES `pluts_accounts`(`id`) ON UPDATE no action ON DELETE no action,\n\tFOREIGN KEY (`entry_id`) REFERENCES `pluts_entries`(`id`) ON UPDATE no action ON DELETE no action\n);\n",
      "\nCREATE INDEX `pluts_amounts_type_idx` ON `pluts_amounts` (`type`);",
      "\nCREATE INDEX `pluts_amounts_account_entry_idx` ON `pluts_amounts` (`account_id`,`entry_id`);",
      "\nCREATE INDEX `pluts_amounts_entry_account_idx` ON `pluts_amounts` (`entry_id`,`account_id`);",
      "\nCREATE TABLE `pluts_entries` (\n\t`id` text PRIMARY KEY NOT NULL,\n\t`description` text NOT NULL,\n\t`date` text NOT NULL,\n\t`commercial_document_id` text,\n\t`commercial_document_type` text,\n\t`posted_at` text NOT NULL\n);\n",
      "\nCREATE INDEX `pluts_entries_date_idx` ON `pluts_entries` (`date`);",
      "\nCREATE INDEX `pluts_entries_commercial_doc_idx` ON `pluts_entries` (`commercial_document_id`,`commercial_document_type`);",
      "\nCREATE TABLE `pluts_entry_keys` (\n\t`key` text PRIMARY KEY NOT NULL,\n\t`entry_id` text NOT NULL,\n\tFOREIGN KEY (`entry_id`) REFERENCES `pluts_entries`(`id`) ON UPDATE no action ON DELETE no action\n);\n"
    ],
    "folderMillis": 1783312166034,
    "hash": "03b3b6d46d68b17c13c86679a4006c814bf91699fcbc2eba0b16cd5aa08a8cea",
    "bps": true
  }
];
