import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const DRIZZLE_DIR = resolve(ROOT, 'drizzle');
const OUT = resolve(ROOT, 'src/db/migrations.ts');

interface JournalEntry {
  tag: string;
  when: number;
  breakpoints: boolean;
}
interface Journal {
  entries: JournalEntry[];
}

/**
 * Reads `./drizzle/meta/_journal.json` + each `./drizzle/<tag>.sql` and emits
 * `src/db/migrations.ts` exporting `MIGRATIONS: MigrationMeta[]`. Mirrors
 * drizzle-orm's `readMigrationFiles` so the embedded runtime runner produces
 * identical hashes to drizzle-orm's own `migrate()`.
 */
async function main(): Promise<void> {
  const journalPath = resolve(DRIZZLE_DIR, 'meta/_journal.json');
  if (!existsSync(journalPath)) {
    throw new Error(`Can't find ${journalPath}. Run \`drizzle-kit generate\` first.`);
  }
  const journal: Journal = JSON.parse(await readFile(journalPath, 'utf8'));

  const migrations = [];
  for (const entry of journal.entries) {
    const sql = await readFile(resolve(DRIZZLE_DIR, `${entry.tag}.sql`), 'utf8');
    const hash = createHash('sha256').update(sql).digest('hex');
    migrations.push({
      sql: sql.split('--> statement-breakpoint'),
      folderMillis: entry.when,
      hash,
      bps: entry.breakpoints,
    });
  }

  const serialized = JSON.stringify(migrations, null, 2);
  const content = `// AUTO-GENERATED by scripts/gen-migrations.ts — do not edit.
// Regenerate via \`bun run db:generate\` (runs drizzle-kit generate + this script).
import type { MigrationMeta } from 'drizzle-orm/migrator';

export const MIGRATIONS: MigrationMeta[] = ${serialized};
`;

  await mkdir(dirname(OUT), { recursive: true });
  await writeFile(OUT, content, 'utf8');
  console.log(`Wrote ${OUT} (${migrations.length} migration(s))`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
